# Generated by Django 4.0.2 on 2022-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('eligibility', models.TextField(default='No Eligibility Criteria Recorded', max_length=800)),
                ('url', models.CharField(max_length=200)),
                ('closing_date', models.DateTimeField()),
                ('gender', models.CharField(choices=[('AN', 'Any'), ('FE', 'Female'), ('MA', 'Male'), ('NB', 'Non-Binary')], default='AN', max_length=2)),
                ('indigenous_status', models.CharField(choices=[('AN', 'Any'), ('AB', 'Aboriginal'), ('AT', 'Aboriginal Torres Strait Islander'), ('NB', 'Not ATSI')], default='AN', max_length=2)),
                ('vision_impairment', models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2)),
                ('low_income', models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2)),
                ('esol', models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2)),
                ('duration', models.CharField(choices=[('AN', 'Any'), ('WO', 'Workshop'), ('BO', 'Boot Camp'), ('UG', 'Undergraduate')], default='AN', max_length=2)),
            ],
        ),
    ]
