# Generated by Django 4.0.2 on 2022-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=600)),
                ('closing_date', models.DateTimeField()),
            ],
        ),
    ]
