# Generated by Django 4.0.2 on 2022-08-31 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarships', '0002_alter_scholarships_image_alter_scholarships_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_scholarships', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
