# Generated by Django 4.0.2 on 2022-09-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_remove_scholarships_category_scholarships_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='category',
        ),
        migrations.AddField(
            model_name='scholarships',
            name='gender',
            field=models.CharField(choices=[('AN', 'Any'), ('FE', 'Female'), ('MA', 'Male'), ('NB', 'Non-Binary')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='indigenous_status',
            field=models.CharField(choices=[('AN', 'Any'), ('AB', 'Aboriginal'), ('AT', 'Aboriginal Torres Strait Islander'), ('NB', 'Not ATSI')], default='AN', max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
