# Generated by Django 4.0.2 on 2022-09-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_remove_scholarships_category_scholarships_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='duration',
            field=models.CharField(choices=[('AN', 'Any'), ('WO', 'Workshop'), ('BO', 'Boot Camp'), ('UG', 'Undergraduate')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='esol',
            field=models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='low_income',
            field=models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='vision_impairment',
            field=models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2),
        ),
    ]
