# Generated by Django 4.0.2 on 2022-09-11 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarships', '0007_scholarships_duration_scholarships_esol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='scholarship_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
