# Generated by Django 4.0.2 on 2022-09-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_scholarships_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='favorites',
        ),
    ]
