# Generated by Django 4.0.2 on 2022-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='duration',
            field=models.CharField(choices=[('AN', 'Any'), ('FI', 'Finance'), ('CO', 'Construction'), ('ED', 'Education'), ('FA', 'Farming_and_Animals'), ('HE', 'Healthcare_and_Medical'), ('HO', 'Hospitality_and_Tourism'), ('IC', 'ICT'), ('LE', 'Legal'), ('RE', 'Real_estate'), ('TR', 'Transport'), ('SE', 'Services_and_Trades')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(choices=[('AN', 'Any'), ('HI', 'Highschool'), ('DI', 'Diploma'), ('BA', 'Bachelor'), ('PO', 'Post_Grad'), ('TE', 'Technical_College')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='esol',
            field=models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('AN', 'Any'), ('FE', 'Female'), ('MA', 'Male'), ('NB', 'Non-Binary')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='indigenous_status',
            field=models.CharField(choices=[('AN', 'Any'), ('AB', 'Aboriginal'), ('AT', 'Aboriginal Torres Strait Islander'), ('NB', 'Not ATSI')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='low_income',
            field=models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_code',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vision_impairment',
            field=models.CharField(choices=[('AN', 'Any'), ('YE', 'Yes'), ('NO', 'No')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_of_birth',
            field=models.IntegerField(default=1990),
        ),
    ]
