# Generated by Django 4.0.2 on 2022-09-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_remove_scholarships_favorites'),
        ('users', '0003_customuser_employment_customuser_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='users', to='scholarships.Scholarships'),
        ),
    ]
