# Generated by Django 4.0.2 on 2022-09-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_remove_scholarships_favorites'),
        ('users', '0004_customuser_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='scholarships.Scholarships'),
        ),
    ]
